<?php

namespace AppBundle\Repository;

/**
 * berufserfahrungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class berufserfahrungRepository extends \Doctrine\ORM\EntityRepository
{
}
