<?php

namespace AppBundle\Repository;

/**
 * bildungsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bildungsRepository extends \Doctrine\ORM\EntityRepository
{
}
