<?php

namespace AppBundle\Repository;

/**
 * engagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class engagementRepository extends \Doctrine\ORM\EntityRepository
{
}
