<?php

namespace AppBundle\Repository;

/**
 * featuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class featuresRepository extends \Doctrine\ORM\EntityRepository
{
}
