<?php

namespace AppBundle\Repository;

/**
 * InfoPersonelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoPersonelRepository extends \Doctrine\ORM\EntityRepository
{
}
