<?php

namespace AppBundle\Repository;

/**
 * interetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class interetRepository extends \Doctrine\ORM\EntityRepository
{
}
