<?php

namespace AppBundle\Repository;

/**
 * IT_kenntnisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IT_kenntnisseRepository extends \Doctrine\ORM\EntityRepository
{
}
